import * as vscode from 'vscode';
import { Configuration } from "../../Configuration";
import { ParseCounts } from '../../FileParser';
import { TestResult, applyTestConfiguration } from "../workspace-suite-shared/expectedResults.helpers";

export function getWs2ExpectedCounts(debug: boolean, wkspUri: vscode.Uri, config: Configuration): ParseCounts {
  const testCount = getWs2ExpectedResults(debug, wkspUri, config).length;
  return { tests: { nodeCount: 78, testCount: testCount }, featureFileCountExcludingEmptyOrCommentedOut: 17, stepFiles: 4, stepMappings: 30 };
}

export const getWs2ExpectedResults = (debug: boolean, wkspUri: vscode.Uri, config: Configuration): TestResult[] => {

  const expectedResults: TestResult[] = [
    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run a successful test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a successful test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run a successful test',
      test_label: 'run a successful test',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run a slow test for async testing',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a slow test for async testing',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run a slow test for async testing',
      test_label: 'run a slow test for async testing',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run another slow test for async testing',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run another slow test for async testing',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run another slow test for async testing',
      test_label: 'run another slow test for async testing',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run a failing test',
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: 'run a failing test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run a failing test',
      test_label: 'run a failing test',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run another successful test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run another successful test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run another successful test',
      test_label: 'run another successful test',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run a test with a missing steps',
      scenario_isOutline: false,
      scenario_result: "Failing step: When we have a missing step ... undefined",
      scenario_scenarioName: 'run a test with a missing steps',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run a test with a missing steps',
      test_label: 'run a test with a missing steps',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/basic.feature',
      scenario_featureName: 'Basic',
      scenario_getLabel: 'run a skipped test',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'run a skipped test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/basic.feature/run a skipped test',
      test_label: 'run a skipped test',
      test_parent: '.../project-2/{{featurePath}}/basic.feature',
      test_uri: '.../project-2/{{featurePath}}/basic.feature'
    }),


    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/contains_regexchars.feature',
      scenario_featureName: 'Containing /[.*+?^${}()|[\\]\\ regex chars',
      scenario_getLabel: 'run a successful scenario containing a characters test /[.*+?^${}()|[\\]\\',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a successful scenario containing a characters test /[.*+?^${}()|[\\]\\',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/contains_regexchars.feature/run a successful scenario containing a characters test /[.*+?^${}()|[\\]\\',
      test_label: 'run a successful scenario containing a characters test /[.*+?^${}()|[\\]\\',
      test_parent: '.../project-2/{{featurePath}}/contains_regexchars.feature',
      test_uri: '.../project-2/{{featurePath}}/contains_regexchars.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/mixed_skip.feature',
      scenario_featureName: 'Mixed skip scenarios',
      scenario_getLabel: 'normal skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'normal skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/mixed_skip.feature/normal skip',
      test_label: 'normal skip',
      test_parent: '.../project-2/{{featurePath}}/mixed_skip.feature',
      test_uri: '.../project-2/{{featurePath}}/mixed_skip.feature'
    }),
    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureName: 'Mixed skip scenarios',
      scenario_featureFileRelativePath: '{{featurePath}}/mixed_skip.feature',
      scenario_getLabel: "don't skip and success",
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: "don't skip and success",
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: ".../project-2/{{featurePath}}/mixed_skip.feature/don't skip and success",
      test_label: "don't skip and success",
      test_parent: '.../project-2/{{featurePath}}/mixed_skip.feature',
      test_uri: '.../project-2/{{featurePath}}/mixed_skip.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: true,
      scenario_featureName: 'Mixed skip scenarios',
      scenario_featureFileRelativePath: '{{featurePath}}/mixed_skip.feature',
      scenario_getLabel: 'fast skip a successful test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'fast skip a successful test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/mixed_skip.feature/fast skip a successful test',
      test_label: 'fast skip a successful test',
      test_parent: '.../project-2/{{featurePath}}/mixed_skip.feature',
      test_uri: '.../project-2/{{featurePath}}/mixed_skip.feature'
    }),
    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureName: 'Mixed skip scenarios',
      scenario_featureFileRelativePath: '{{featurePath}}/mixed_skip.feature',
      scenario_getLabel: "don't skip and fail",
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: "don't skip and fail",
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: ".../project-2/{{featurePath}}/mixed_skip.feature/don't skip and fail",
      test_label: "don't skip and fail",
      test_parent: '.../project-2/{{featurePath}}/mixed_skip.feature',
      test_uri: '.../project-2/{{featurePath}}/mixed_skip.feature'
    }),
    new TestResult({
      scenario_fastSkipTag: true,
      scenario_featureName: 'Mixed skip scenarios',
      scenario_featureFileRelativePath: '{{featurePath}}/mixed_skip.feature',
      scenario_getLabel: 'fast skip a failing test',
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: 'fast skip a failing test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/mixed_skip.feature/fast skip a failing test',
      test_label: 'fast skip a failing test',
      test_parent: '.../project-2/{{featurePath}}/mixed_skip.feature',
      test_uri: '.../project-2/{{featurePath}}/mixed_skip.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/skipped.feature',
      scenario_featureName: 'skipped feature',
      scenario_getLabel: 'normal skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'normal skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/skipped.feature/normal skip',
      test_label: 'normal skip',
      test_parent: '.../project-2/{{featurePath}}/skipped.feature',
      test_uri: '.../project-2/{{featurePath}}/skipped.feature'
    }),


    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/duplicate.feature',
      scenario_featureName: 'Duplicate',
      scenario_getLabel: 'run a test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/duplicate.feature/run a test',
      test_label: 'run a test',
      test_parent: '.../project-2/{{featurePath}}/duplicate.feature',
      test_uri: '.../project-2/{{featurePath}}/duplicate.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: true,
      scenario_featureFileRelativePath: '{{featurePath}}/fastskip_feature.feature',
      scenario_featureName: 'fast skip feature',
      scenario_getLabel: 'fast skip by feature',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'fast skip by feature',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/fastskip_feature.feature/fast skip by feature',
      test_label: 'fast skip by feature',
      test_parent: '.../project-2/{{featurePath}}/fastskip_feature.feature',
      test_uri: '.../project-2/{{featurePath}}/fastskip_feature.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/duplicate.feature',
      scenario_featureName: 'Duplicate',
      scenario_getLabel: 'run a test',
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: 'run a test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/duplicate.feature/run a test',
      test_label: 'run a test',
      test_parent: '.../project-2/{{featurePath}}/grouped/duplicate.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/duplicate.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Success',
      scenario_isOutline: true,
      scenario_result: 'passed',
      scenario_scenarioName: 'Blenders Success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Success',
      test_label: 'Blenders Success',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Fail',
      scenario_isOutline: true,
      scenario_result: 'Failing step: Then it should transform into "FAIL" ... failed\nTraceback (most recent call last):\n  File -snip- assert context.blender.result == other_thing\nAssertionError',
      scenario_scenarioName: 'Blenders Fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Fail',
      test_label: 'Blenders Fail',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Fail 2',
      scenario_isOutline: true,
      scenario_result: 'Failing step: Then it should transform into "FAIL" ... failed\nTraceback (most recent call last):\n  File -snip- assert context.blender.result == other_thing\nAssertionError',
      scenario_scenarioName: 'Blenders Fail 2',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Fail 2',
      test_label: 'Blenders Fail 2',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: true,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Fast Skip a Failure',
      scenario_isOutline: true,
      scenario_result: 'Failing step: Then it should transform into "FAIL" ... failed\nTraceback (most recent call last):\n  File -snip- assert context.blender.result == other_thing\nAssertionError',
      scenario_scenarioName: 'Blenders Fast Skip a Failure',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Fast Skip a Failure',
      test_label: 'Blenders Fast Skip a Failure',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: true,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Fast Skip a Success',
      scenario_isOutline: true,
      scenario_result: 'passed',
      scenario_scenarioName: 'Blenders Fast Skip a Success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Fast Skip a Success',
      test_label: 'Blenders Fast Skip a Success',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Skip',
      scenario_isOutline: true,
      scenario_result: 'skipped',
      scenario_scenarioName: 'Blenders Skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Skip',
      test_label: 'Blenders Skip',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_mixed.feature',
      scenario_featureName: 'Mixed outline',
      scenario_getLabel: 'Blenders Success 2',
      scenario_isOutline: true,
      scenario_result: 'passed',
      scenario_scenarioName: 'Blenders Success 2',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature/Blenders Success 2',
      test_label: 'Blenders Success 2',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_mixed.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_success.feature',
      scenario_featureName: 'Outline success',
      scenario_getLabel: 'Blend Success',
      scenario_isOutline: true,
      scenario_result: 'passed',
      scenario_scenarioName: 'Blend Success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_success.feature/Blend Success',
      test_label: 'Blend Success',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_success.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_success.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/outline_success.feature',
      scenario_featureName: 'Outline success',
      scenario_getLabel: 'Blend Success 2',
      scenario_isOutline: true,
      scenario_result: 'passed',
      scenario_scenarioName: 'Blend Success 2',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/outline_success.feature/Blend Success 2',
      test_label: 'Blend Success 2',
      test_parent: '.../project-2/{{featurePath}}/grouped/outline_success.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/outline_success.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/table.feature',
      scenario_featureName: 'Table feature',
      scenario_getLabel: 'Use a table (fail)',
      scenario_isOutline: false,
      scenario_result: 'Failing step: Then we will find 25 people in "Testers" ... failed\nTraceback (most recent call last):\n  File -snip- assert int(count) == sum(1 for ud in context.userDepts if ud.dept == dept)\nAssertionError',
      scenario_scenarioName: 'Use a table (fail)',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/table.feature/Use a table (fail)',
      test_label: 'Use a table (fail)',
      test_parent: '.../project-2/{{featurePath}}/grouped/table.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/table.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/table.feature',
      scenario_featureName: 'Table feature',
      scenario_getLabel: 'Use a table (success)',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'Use a table (success)',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/table.feature/Use a table (success)',
      test_label: 'Use a table (success)',
      test_parent: '.../project-2/{{featurePath}}/grouped/table.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/table.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/textblock.feature',
      scenario_featureName: 'Text block',
      scenario_getLabel: 'run a failing textblock test',
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: 'run a failing textblock test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/textblock.feature/run a failing textblock test',
      test_label: 'run a failing textblock test',
      test_parent: '.../project-2/{{featurePath}}/grouped/textblock.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/textblock.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/grouped/textblock.feature',
      scenario_featureName: 'Text block',
      scenario_getLabel: 'run a successful textblock test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a successful textblock test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/grouped/textblock.feature/run a successful textblock test',
      test_label: 'run a successful textblock test',
      test_parent: '.../project-2/{{featurePath}}/grouped/textblock.feature',
      test_uri: '.../project-2/{{featurePath}}/grouped/textblock.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'create a before hook-error',
      scenario_isOutline: false,
      scenario_result: 'Traceback:\n  File -snip- raise Exception("error in before_scenario hook")',
      scenario_scenarioName: 'create a before hook-error',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/create a before hook-error',
      test_label: 'create a before hook-error',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'normal skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'normal skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/normal skip',
      test_label: 'normal skip',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'skip a before hook-error',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'skip a before hook-error',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/skip a before hook-error',
      test_label: 'skip a before hook-error',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'create a before hook-error again',
      scenario_isOutline: false,
      scenario_result: 'Traceback:\n  File -snip- raise Exception("error in before_scenario hook")',
      scenario_scenarioName: 'create a before hook-error again',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/create a before hook-error again',
      test_label: 'create a before hook-error again',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'create an after hook-error',
      scenario_isOutline: false,
      scenario_result: 'Traceback:\n  File -snip- raise Exception("error in after_scenario hook")',
      scenario_scenarioName: 'create an after hook-error',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/create an after hook-error',
      test_label: 'create an after hook-error',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'another normal skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'another normal skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/another normal skip',
      test_label: 'another normal skip',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'skip an after hook-error',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'skip an after hook-error',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/skip an after hook-error',
      test_label: 'skip an after hook-error',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '...features/feature_with_hook_error.feature',
      scenario_featureName: 'With a hook-error',
      scenario_getLabel: 'create an after hook-error again',
      scenario_isOutline: false,
      scenario_result: 'Traceback:\n  File -snip- raise Exception("error in after_scenario hook")',
      scenario_scenarioName: 'create an after hook-error again',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/feature_with_hook_error.feature/create an after hook-error again',
      test_label: 'create an after hook-error again',
      test_parent: '.../project-2/{{featurePath}}/feature_with_hook_error.feature',
      test_uri: '.../project-2/{{featurePath}}/feature_with_hook_error.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'simple step',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'simple step',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/simple step',
      test_label: 'simple step',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'simple step with more text',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'simple step with more text',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/simple step with more text',
      test_label: 'simple step with more text',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'a cased step',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'a cased step',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/a cased step',
      test_label: 'a cased step',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'param step',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'param step',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/param step',
      test_label: 'param step',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'param step with more text',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'param step with more text',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/param step with more text',
      test_label: 'param step with more text',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'two param step no1',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'two param step no1',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/two param step no1',
      test_label: 'two param step no1',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'two param step no2',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'two param step no2',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/two param step no2',
      test_label: 'two param step no2',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'step with param',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'step with param',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/step with param',
      test_label: 'step with param',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'step without custom flag type',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'step without custom flag type',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/step without custom flag type',
      test_label: 'step without custom flag type',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'step with custom flag type present',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'step with custom flag type present',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/step with custom flag type present',
      test_label: 'step with custom flag type present',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'yet another step',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'yet another step',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/yet another step',
      test_label: 'yet another step',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: '"yet" "another" step double quoted',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '"yet" "another" step double quoted',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/"yet" "another" step double quoted',
      test_label: '"yet" "another" step double quoted',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: "'yet' 'another' step single quoted",
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: "'yet' 'another' step single quoted",
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: ".../project-2/{{featurePath}}/goto_step.feature/'yet' 'another' step single quoted",
      test_label: "'yet' 'another' step single quoted",
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'wrapped step 1',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'wrapped step 1',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/wrapped step 1',
      test_label: 'wrapped step 1',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'wrapped step 2',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'wrapped step 2',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/wrapped step 2',
      test_label: 'wrapped step 2',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature',
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: '{{featurePath}}/goto_step.feature',
      scenario_featureName: 'Go to Step def tests',
      scenario_getLabel: 'wrapped step 3',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'wrapped step 3',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/{{featurePath}}/goto_step.feature/wrapped step 3',
      test_label: 'wrapped step 3',
      test_parent: '.../project-2/{{featurePath}}/goto_step.feature',
      test_uri: '.../project-2/{{featurePath}}/goto_step.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: 'features/nested/nested1.faildupe.feature',
      scenario_featureName: 'Duplicate',
      scenario_getLabel: 'run a test',
      scenario_isOutline: false,
      scenario_result: 'Failing step: When we implement a failing test ... failed\nTraceback (most recent call last):\n  File -snip- assert successful_or_failing == "successful"\nAssertionError',
      scenario_scenarioName: 'run a test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/features/nested/nested1.faildupe.feature/run a test',
      test_label: 'run a test',
      test_parent: '.../project-2/features/nested/nested1.faildupe.feature',
      test_uri: '.../project-2/features/nested/nested1.faildupe.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: 'features/nested/nested/nested/nested3.sucessdupe.feature',
      scenario_featureName: 'Duplicate',
      scenario_getLabel: 'run a test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/features/nested/nested/nested/nested3.sucessdupe.feature/run a test',
      test_label: 'run a test',
      test_parent: '.../project-2/features/nested/nested/nested/nested3.sucessdupe.feature',
      test_uri: '.../project-2/features/nested/nested/nested/nested3.sucessdupe.feature'
    }),

    new TestResult({
      scenario_fastSkipTag: false,
      scenario_featureFileRelativePath: 'features/nested/nested/nested2.successdupe.feature',
      scenario_featureName: 'Duplicate',
      scenario_getLabel: 'run a test',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'run a test',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../project-2/features/nested/nested/nested2.successdupe.feature/run a test',
      test_label: 'run a test',
      test_parent: '.../project-2/features/nested/nested/nested2.successdupe.feature',
      test_uri: '.../project-2/features/nested/nested/nested2.successdupe.feature'
    }),

  ];


  const wkspSettings = config.workspaceSettings[wkspUri.path];
  return applyTestConfiguration(debug, wkspSettings, expectedResults);
}


