import { ProjParseCounts } from "../../../parsers/fileParser";
import { TestResult } from "../_common/types"

export function getExpectedCounts(): ProjParseCounts {
  const testCount = getExpectedResultsForNoTagsSpecified().length;
  return {
    tests: { nodeCount: 14, testCount: testCount },
    featureFilesExceptEmptyOrCommentedOut: 1, stepFilesExceptEmptyOrCommentedOut: 3,
    stepFileStepsExceptCommentedOut: 7, featureFileStepsExceptCommentedOut: 39, stepMappings: 39
  };
}



export const getExpectedResultsForNoTagsSpecified = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

  ];



  return expectedResults;
}



export const getExpectedResultsForTag1RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [


    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];



  return expectedResults;
}



export const getExpectedResultsForTag2RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];



  return expectedResults;
}



export const getExpectedResultsForTag1orTag2RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];

  return expectedResults;
}



export const getExpectedResultsForTag1andTag2RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];

  return expectedResults;
}



export const getExpectedResultsForTag1orTag2andTag3RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];

  return expectedResults;
}



export const getExpectedResultsForNotTag1andNotTag2RunProfile = (): TestResult[] => {

  const expectedResults: TestResult[] = [

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'all tags - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'all tags - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/all tags - success - check tags and envvars',
      test_label: 'all tags - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - success - check tags and envvars',
      scenario_isOutline: false,
      scenario_result: 'passed',
      scenario_scenarioName: 'untagged - success - check tags and envvars',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - success - check tags and envvars',
      test_label: 'untagged - success - check tags and envvars',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - fail',
      scenario_isOutline: false,
      scenario_result: 'failed',
      scenario_scenarioName: 'untagged - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - fail',
      test_label: 'untagged - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: 'untagged - @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: 'untagged - @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/untagged - @skip - skip',
      test_label: 'untagged - @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag2 - success - stage check',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @tag2 - success - stage check',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag2 - success - stage check',
      test_label: '@tag1 @tag2 - success - stage check',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - success',
      test_label: '@tag1 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 - fail',
      test_label: '@tag1 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @skip - skip',
      test_label: '@tag1 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - success',
      test_label: '@tag2 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 - fail',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 - fail',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 - fail',
      test_label: '@tag2 - fail',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @skip - skip',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @skip - skip',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @skip - skip',
      test_label: '@tag2 @skip - skip',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag1 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag1 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag1 @tag3 - success',
      test_label: '@tag1 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),

    new TestResult({
      scenario_featureFileRelativePath: 'features/tags_and_vars.feature',
      scenario_featureName: 'Tags and Vars',
      scenario_getLabel: '@tag2 @tag3 - success',
      scenario_isOutline: false,
      scenario_result: 'skipped',
      scenario_scenarioName: '@tag2 @tag3 - success',
      test_children: undefined,
      test_description: undefined,
      test_error: undefined,
      test_id: '.../run profiles/features/tags_and_vars.feature/@tag2 @tag3 - success',
      test_label: '@tag2 @tag3 - success',
      test_parent: '.../run profiles/features/tags_and_vars.feature',
      test_uri: '.../run profiles/features/tags_and_vars.feature',
    }),


  ];

  return expectedResults;
}


